


package net.alepuzio.mms.domain.enumeration;

public enum EnumWord {
	UNKOWN("NESSUNA PAROLA")
	,ZERO("SASSO")
	, UNO("SEDIA") 
	, DUE("SENO")
	, TRE("SCIMMIA")
	, QUATTRO("SERA")
	, CINQUE("ISOLA")
	, SEI("SAGGIO")
	, SETTE("SECCHIO")
	, OTTO("SAVOIA") 
	  , NOVE("SPIA")
	 /** Error : The literal 08 of type int is out of range.
	 * Solution in different type like String , 
	 * read https://stackoverflow.com/questions/970039/09-is-not-recognized-where-as-9-is-recognized */	
	, DIECI("TAZZE")
	, UNDICI("DADI")
	, DODICI("DNA")
	, TREDICI("DAMA")
	, QUATTORDICI("TORRE")
	, QUINDI("DUELLO")
	, SEDICI("DUCE")
	, DICIASETTE("DIGA")
	, DICIOTTO("TUFFO")
	, DICIANNOVE("TAPPI")
	, VENTI("NASO")
	
	, VENTIUNO("NUDO")
	, VENTIDUE("NONNA")
	, VENTITRE("ANIMA")
	, VENTIQUATTRO("NERO")
	, VENTICINQUE("ANELLO")
	, VENTISEI("NOCI")
	, VENTISETTE("GNOCCHI")
	, VENTIOTTO("NEVE")
	, VENTINOVE("NUBI")
	, TRENTA("MASSAIA")
	
	, TRENTAUNO("MOTO")
	, TRENTADUE("MANO")
	, TRENTATRE("MUMMIA")
	, TRENTAQUATTRO("MURO")
	, TRENTACINQUE("MELA")
	, TRENTASEI("MICIO")
	, TRENTASETTE("MUCCA")
	, TRENTOTTO("MAFIA")
	, TRENTANOVE("AMBO")
	, QUARANTA("RASOIO")

	, QUARANTAUNO("RODEO")
	, QUARANTADUE("RANA")
	, QUARANTATRE("ROMA")
	, QUARANTAQUATTRO("ORRORE")
	, QUARANTACINQUE("RALLY")
	, QUARANTASEI("ROCCIA")
	, QUARANTASETTE("ORCA")
	, QUARANTOTTO("ROVI")
	, QUARANTANOVA("RABBIA")
	, CINQUANTA("LISCIO")

	, CINQUANTUNO("LETTO")
	, CINQUANTADUE("LEONE")
	, CINQUANTATRE("LAMA")
	, CINQUANTAQUATTRO("LIRE")
	, CINQUANTACINQUE("LILLY")
	, CINQUANTASEI("LACCI")
	, CINQUANTASETTE("LAGO")
	, CINQUANTAOTTO("LAVA")
	, CINQUANTANOVA("LUPO")
	, SESSANTA("CESSO")



	,	SESSANTUNO ("CD")
	,	SESSANTADUE ("CIGNO")
	,	SESSANTATRE ("CIME")
	,	SESSANTAQUATTRO ("CERO")
	,	SESSANTACINQUE ("GIGLIO")
	,	SESSANTASEI ("CIUCCIO")
	,	SESSANTASETTE ("CICCHE")
	,	SESSANTOTTO ("GIOVE")
	,	SESSANTANOVA ("CIP - di Ciop")
	,	SETTANTA ("CASSA")
	
	,	SETTANTUNO  ("CHIODI")
	,	SETTANTADUE  ("CANE")
	,	SETTANTATRE  ("GOMMA")
	,	SETTANTAQUATTRO  ("GUERRA")
	,	SETTANTACINQUE  ("AQUILA")
	,	SETTANTASEI  ("GHIACCIO")
	,	SETTANTASETTE  ("COCCO")
	,	SETTANTOTTO  ("CHIAVE")
	,	SETTANTANOVE  ("COPPE") 
	,	OTTANTA ("VASO")
	,	OTTANTUNO ("FETO")
	,	OTTANTADUE ("FÒN")
	,	OTTANTATRE ("FIUME")
	,	OTTANTAQUATTRO ("FARO")
	,	OTTANTACINQUE ("FOGLIE")
	,	OTTANTASEI ("FACCIA")
	,	OTTANTASETTE ("FUOCO")
	,	OTTANTOTTO ("FAVA")
	,	OTTANTANOVE ("VIP")
	,	NOVANTA ("PIZZA")

	,	NOVANTUNO("PIEDE")   
	,	NOVANTADUE("PANE ")
	,	NOVANTATRE("PIUMA")   
	,	NOVANTAQUATTRO("PERA")
	,	NOVANTACINQUE("BIGLIA")
	,	NOVANTASEI("BICI ")
	,	NOVANTASETTE("PACCO")
	,	NOVANTOTTO("PUFFO") 
	,	NOVANTANOVE("PIPPO")
	
	;
/*
	*/
	private String word;
	
	private EnumWord(String newImage  ){
		this.word = newImage;
	}

	public String word() {
		return this.word;
	}
	
	
	
	
}

