package net.alepuzio.mms.domain.enumeration;

public enum EnumPhoneticSound {
	UNKOWN("UNKWON"),
	ZERO("SS"), UNO("SD"), DUE("SN"), TRE("SCM"), QUATTRO("SR"), CINQUE("SL"), SEI("SG"), SETTE("SCH"), OTTO( "SV") , NOVE( "SP")
	/*
	 *  Error : The literal 08 of type int is out of
	 * range. Solution in different type like String , read
	 * https://stackoverflow.com/questions/970039/09-is-not-recognized-where-as-
	 * 9-is-recognized
	 */
	, DIECI("TZ"), UNDICI("DD"), DODICI("DN"), TREDICI("DM"), QUATTORDICI("TR"), QUINDI("DL"), SEDICI("DC"), DICIASETTE("DGH"), DICIOTTO("TF"), DICIANNOVE("TP"), VENTI("NS")

	, VENTIUNO("ND"), VENTIDUE("NN"), VENTITRE("NM"), VENTIQUATTRO("NR"), VENTICINQUE("NL"), VENTISEI("NC"), VENTISETTE("GNCH"), VENTIOTTO(" NV"), VENTINOVE("NB"), TRENTA(" MS")

	, TRENTAUNO("MT"), TRENTADUE("MN"), TRENTATRE("MM"), TRENTAQUATTRO("MR"), TRENTACINQUE("ML"), TRENTASEI("MC"), TRENTASETTE("MCH"), TRENTOTTO("MF"), TRENTANOVE("MB"), QUARANTA("RS")

	, QUARANTAUNO("RD"), QUARANTADUE("RN"), QUARANTATRE("RM"), QUARANTAQUATTRO("RR"), QUARANTACINQUE("RL"), QUARANTASEI("RC"), QUARANTASETTE("RCH"), QUARANTOTTO("RV"), QUARANTANOVA("RB"), CINQUANTA("LSC")

	, CINQUANTUNO("LT"), CINQUANTADUE("LN"), CINQUANTATRE("LM"), CINQUANTAQUATTRO("LR"), CINQUANTACINQUE("LL"), CINQUANTASEI("LC"), CINQUANTASETTE("LGH"), CINQUANTAOTTO("LV"), CINQUANTANOVA("LP"), SESSANTA("CS")

	, SESSANTUNO("CD"), SESSANTADUE("CGN"), SESSANTATRE("CM"), SESSANTAQUATTRO("CR"), SESSANTACINQUE("GGL"), SESSANTASEI("CC"), SESSANTASETTE("CCH"), SESSANTOTTO("GV"), SESSANTANOVA("CIP - di Ciop"), SETTANTA("CHS")

	, SETTANTUNO("CHD"), SETTANTADUE("CHN"), SETTANTATRE("GHM"), SETTANTAQUATTRO("GHR"), SETTANTACINQUE("QL"), SETTANTASEI("GHC"), SETTANTASETTE("CHCH"), SETTANTOTTO("CHV"), SETTANTANOVE("CHP"), OTTANTA("VS"), OTTANTUNO("FT"), OTTANTADUE("FN"), OTTANTATRE("FM"), OTTANTAQUATTRO("FR"), OTTANTACINQUE("FGL"), OTTANTASEI("FC"), OTTANTASETTE("FCH"), OTTANTOTTO("FV"), OTTANTANOVE("VP"), NOVANTA("PZ")

	, NOVANTUNO("PD"), NOVANTADUE("PN"), NOVANTATRE("PM"), NOVANTAQUATTRO("PR"), NOVANTACINQUE("BGL"), NOVANTASEI("BC"), NOVANTASETTE("PCH"), NOVANTOTTO("PF"), NOVANTANOVE("PP")

	;
	/*
		*/
	private String phonetic;// TODO print the associated sound

	private EnumPhoneticSound(String newPhonetic) {
		this.phonetic = newPhonetic;
	}

	public String value() {
		return this.phonetic;
	}
}
